### PR TITLE
Add Example Use-case

### PR DESCRIPTION
**Pull request by danielogen**
This PR adds a use-case where the developer integrates only portion of the code snippet suggested by ChatGPT

### CODE REVIEW

**Comment by johnxu21** [comment]
It would be nice to define program synthesis as well as in what context it applies to the example you have provided

**Comment by danielogen** [comment]
> It would be nice to define program synthesis as well as in what context it applies to the example you have provided

True, I also thought of it but I forgot to write :)

**Comment by johnxu21** [comment]
Still waiting :-)

**Comment by johnxu21** [comment]
Please submit

**Pull request merged**
